### ISSUE TITLE
Not working with Ventura?

### ISSUE THREAD

**Issue by UPKDev** [pirj/nobacklight#1]
HI, I have installed it, but it's not working. After opening the lid there is always the not fully dimmed Display visable (as with no nobacklight installed). Mac OS is Vebtura 13.3.1 (a) (22E772610a). The machine is a MacBook Pro M1 2020 with external Benq Monitor and 'noclamshell' installed, which works perfectly.

**Comment by pirj** [comment]
What would ‘brightness -l 2’ return?

**Comment by UPKDev** [comment]
***@***.*** ~ % clear
***@***.*** ~ % brightness -l 2
usage: brightness [-m|-d display] [-v] <brightness>
   or: brightness -l [-v]
***@***.*** ~ %
***@***.*** ~ %
***@***.*** ~ % brightness -l
display 0: main, active, awake, online, external, ID 0x2
brightness: failed to get brightness of display 0x2 (error -536870201)
display 1: inactive, awake, online, built-in, ID 0x1
brightness: failed to get brightness of display 0x1 (error -536870201)
***@***.*** ~ %
***@***.*** ~ %
***@***.*** ~ % brightness -l -v
display 0: main, active, awake, online, external, ID 0x2
	resolution 2560 x 1440 pt (2560 x 1440 px) @ 60.0 Hz, origin (0, 0)
	physical size 602 x 339 mm
	IOKit flags 0x2000007; IOKit display mode ID 0x19
	mirrored
	usable for desktop GUI, uses OpenGL acceleration
brightness: failed to get brightness of display 0x2 (error -536870201)
display 1: inactive, awake, online, built-in, ID 0x1
	resolution 2560 x 1440 pt (2560 x 1440 px) @ 60.0 Hz, origin (0, 0)
	physical size 279 x 152 mm
	IOKit flags 0x200003; IOKit display mode ID 0x8
	mirrors display ID 0x2
	usable for desktop GUI, uses OpenGL acceleration
brightness: failed to get brightness of display 0x1 (error -536870201)
***@***.*** ~ %

**Comment by pirj** [comment]
My bad, `2&>/dev/null` is unrelated, and `brightness -l` is the one to run.

What happens if you run the script from the command line manually?
What are the vars values?
Would `brightness -d 1 -v 0` dim the internal display?

**Comment by UPKDev** [comment]
> What happens if you run the script from the command line manually?
> 
REM: brew puts brightness to /opt/homebrew/Cellar/brightness/1.2/bin/brightness
so after adjusting the script to the right path:

***@***.*** .bin % ./nobacklight
/opt/homebrew/Cellar/brightness/1.2/bin/brightness: failed to set brightness of display 0x1 (error -536870201)
***@***.*** .bin %


> Would brightness -d 1 -v 0 dim the internal display?
> 

No:
***@***.*** ~ % brightness -d 1 -v 0
brightness: failed to set brightness of display 0x1 (error -536870201)
***@***.***

sorry.

**Comment by pirj** [comment]
Binaries are installed to /usr/local/bin by Homebrew on my machine.
Wondering if it would work to run it from the script as just `brightness` with no path. Probably this wouldn't work when it runs as a service with no `$PATH` set by Homebrew.

For the problem with brightness, I suggest opening an issue in their issue tracker.
Thanks for understanding.
